export enum AssetCriticality {
  CRITICAL = 'CRITICAL',
  STANDARD = 'STANDARD',
  NON_CRITICAL = 'NON_CRITICAL',
}

export enum AssetStatus {
  OPERATIONAL = 'OPERATIONAL',
  IN_MAINTENANCE = 'IN_MAINTENANCE',
  MAINTENANCE_BLOCKED = 'MAINTENANCE_BLOCKED',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  DECOMMISSIONED = 'DECOMMISSIONED',
}
