export enum DocumentEntityType {
  ASSET = 'ASSET',
  PART = 'PART',
  PREVENTIVE_PLAN = 'PREVENTIVE_PLAN',
  WORK_ORDER = 'WORK_ORDER',
  INTERVENTION = 'INTERVENTION',
}

export enum DocumentType {
  TECHNICAL_MANUAL = 'TECHNICAL_MANUAL',
  SCHEMATIC = 'SCHEMATIC',
  INSTALLATION_REPORT = 'INSTALLATION_REPORT',
  SAFETY_DATA_SHEET = 'SAFETY_DATA_SHEET',
  SPECIFICATION_SHEET = 'SPECIFICATION_SHEET',
  PROCEDURE_DOCUMENT = 'PROCEDURE_DOCUMENT',
  CONTRACTOR_REPORT = 'CONTRACTOR_REPORT',
  PHOTO = 'PHOTO',
  COMPLIANCE_CERTIFICATE = 'COMPLIANCE_CERTIFICATE',
}

export enum CertificateType {
  PRESSURE_VESSEL = 'PRESSURE_VESSEL',
  ELECTRICAL_INSTALLATION = 'ELECTRICAL_INSTALLATION',
  LIFTING_EQUIPMENT = 'LIFTING_EQUIPMENT',
  FIRE_SAFETY = 'FIRE_SAFETY',
  OTHER = 'OTHER',
}

export enum CertificateStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
}
