export enum InterventionActionType {
  INSPECTION = 'INSPECTION',
  REPAIR = 'REPAIR',
  REPLACEMENT = 'REPLACEMENT',
  CALIBRATION = 'CALIBRATION',
  LUBRICATION = 'LUBRICATION',
  CLEANING = 'CLEANING',
}

export enum InterventionResult {
  RESOLVED = 'RESOLVED',
  PARTIALLY_RESOLVED = 'PARTIALLY_RESOLVED',
  NEEDS_FOLLOW_UP = 'NEEDS_FOLLOW_UP',
  COULD_NOT_INTERVENE = 'COULD_NOT_INTERVENE',
}

export enum ChecklistItemStatus {
  PENDING = 'PENDING',
  DONE = 'DONE',
  ANOMALY_DETECTED = 'ANOMALY_DETECTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum ChecklistTaskType {
  INSPECTION = 'INSPECTION',
  MEASUREMENT = 'MEASUREMENT',
  LUBRICATION = 'LUBRICATION',
  CLEANING = 'CLEANING',
  REPLACEMENT = 'REPLACEMENT',
  CALIBRATION = 'CALIBRATION',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum PreventiveFrequencyType {
  FIXED_INTERVAL_DAYS = 'FIXED_INTERVAL_DAYS',
  CALENDAR = 'CALENDAR',
}
