export enum UrgencyPerception {
  MACHINE_STOPPED = 'MACHINE_STOPPED',
  ABNORMAL_BEHAVIOR = 'ABNORMAL_BEHAVIOR',
  MINOR_ISSUE = 'MINOR_ISSUE',
}

export enum ProblemReportStatus {
  PENDING = 'PENDING',
  CONVERTED = 'CONVERTED',
  REJECTED = 'REJECTED',
  DEFERRED = 'DEFERRED',
  ARCHIVED = 'ARCHIVED',
}

export enum ReportRejectionReason {
  INVALID_REPORT = 'INVALID_REPORT',
  UNSUPPORTED_EQUIPMENT = 'UNSUPPORTED_EQUIPMENT',
  ALREADY_ADDRESSED = 'ALREADY_ADDRESSED',
  DUPLICATE_EXISTING_WO = 'DUPLICATE_EXISTING_WO',
  OUT_OF_MAINTENANCE_SCOPE = 'OUT_OF_MAINTENANCE_SCOPE',
}

export enum ReportArchiveReason {
  RESOLVED_SPONTANEOUSLY = 'RESOLVED_SPONTANEOUSLY',
  EQUIPMENT_DECOMMISSIONED = 'EQUIPMENT_DECOMMISSIONED',
  SUBMITTED_IN_ERROR = 'SUBMITTED_IN_ERROR',
  REPLACED_BY_OTHER_WO = 'REPLACED_BY_OTHER_WO',
  MANAGEMENT_DECISION = 'MANAGEMENT_DECISION',
}
