export enum WorkOrderType {
  CORRECTIVE = 'CORRECTIVE',
  PREVENTIVE = 'PREVENTIVE',
}

export enum WorkOrderPriority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum WorkOrderStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum WorkOrderSource {
  PROBLEM_REPORT = 'PROBLEM_REPORT',
  DIRECT_CREATION = 'DIRECT_CREATION',
  PREVENTIVE_PLAN = 'PREVENTIVE_PLAN',
}

export enum AssignmentRole {
  PRINCIPAL = 'PRINCIPAL',
  CONTRIBUTOR = 'CONTRIBUTOR',
}

export enum OnHoldReasonType {
  MISSING_PART = 'MISSING_PART',
  EXTERNAL_CONTRACTOR = 'EXTERNAL_CONTRACTOR',
  ACCESS_DENIED = 'ACCESS_DENIED',
  OTHER = 'OTHER',
}

export enum WOCancellationReason {
  DUPLICATE = 'DUPLICATE',
  EQUIPMENT_DECOMMISSIONED = 'EQUIPMENT_DECOMMISSIONED',
  RESOLVED_OTHERWISE = 'RESOLVED_OTHERWISE',
  CREATED_IN_ERROR = 'CREATED_IN_ERROR',
  EXTERNAL_DECISION = 'EXTERNAL_DECISION',
}

export enum WOReassignmentReason {
  TECHNICIAN_OVERLOADED = 'TECHNICIAN_OVERLOADED',
  TECHNICIAN_ABSENT = 'TECHNICIAN_ABSENT',
  SPECIFIC_SKILL_REQUIRED = 'SPECIFIC_SKILL_REQUIRED',
  PRIORITY_CONFLICT = 'PRIORITY_CONFLICT',
  OTHER = 'OTHER',
}

export enum ValidationRejectionReason {
  INSUFFICIENT_DESCRIPTION = 'INSUFFICIENT_DESCRIPTION',
  PARTS_USED_MISMATCH = 'PARTS_USED_MISMATCH',
  INCONSISTENT_TIME = 'INCONSISTENT_TIME',
  INCOMPLETE_CHECKLIST = 'INCOMPLETE_CHECKLIST',
  OTHER = 'OTHER',
}
